-- Criar o usuário admin diretamente usando a extensão auth
-- Primeiro, vamos inserir o usuário na tabela auth.users

INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'a1b2c3d4-e5f6-7890-1234-567890abcdef'::uuid,
  'authenticated',
  'authenticated',
  'hudsonluizdacruz@gmail.com',
  crypt('HudsoN12H*', gen_salt('bf')),
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NOW(),
  '{"provider": "email", "providers": ["email"]}',
  '{}',
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  '',
  0,
  NULL,
  '',
  NULL,
  false,
  NULL
) ON CONFLICT (email) DO NOTHING;

-- Inserir o perfil admin correspondente
INSERT INTO public.profiles (id, nome, email, tipo_usuario)
VALUES (
  'a1b2c3d4-e5f6-7890-1234-567890abcdef'::uuid,
  'Admin Sistema',
  'hudsonluizdacruz@gmail.com',
  'admin'
) ON CONFLICT (email) DO UPDATE SET 
  tipo_usuario = 'admin',
  nome = 'Admin Sistema';